export default {
  head: {
    script: [
      { src: '/codemirror.js' },
      { src: '/mode/javascript/javascript.js' },
      { src: '/addon/mode/loadmode.js' },
      { src: '/addon/mode/simple.js' },
      { src: '/addon/mode/overlay.js' },
      { src: '/addon/selection/active-line.js' },
    ],
    link: [{
      rel: 'stylesheet',
      href: '/codemirror.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/ttcn.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/3024-day.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/3024-night.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/abcdef.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/ambiance-mobile.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/ambiance.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/base16-dark.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/base16-light.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/bespin.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/blackboard.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/cobalt.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/colorforth.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/darcula.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/dracula.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/duotone-dark.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/duotone-light.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/eclipse.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/elegant.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/erlang-dark.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/gruvbox-dark.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/hopscotch.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/icecoder.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/idea.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/isotope.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/lesser-dark.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/liquibyte.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/lucario.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/material-darker.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/material-ocean.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/material-palenight.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/material.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/mbo.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/mdn-like.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/midnight.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/monokai.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/moxer.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/neat.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/neo.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/night.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/nord.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/oceanic-next.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/panda-syntax.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/paraiso-dark.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/paraiso-light.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/pastel-on-dark.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/railscasts.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/rubyblue.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/seti.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/shadowfox.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/solarized.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/ssms.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/the-matrix.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/tomorrow-night-bright.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/tomorrow-night-eighties.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/twilight.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/vibrant-ink.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/xq-dark.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/xq-light.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/yeti.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/yonce.css',
    }, {
      rel: 'stylesheet',
      href: '/theme/zenburn.css',
    }],
  },
  modules: [
    '@nuxtjs/tailwindcss',
  ],
};
